In [1]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


In [3]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.mean(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.46317933929082467 0.9949820023471365 0.46317933929082467


In [4]:
A = np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [6]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [7]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [9]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.48431741 0.53342719 0.91787099]
  [0.61619646 0.12996007 0.00488271]
  [0.891785   0.46144197 0.53868323]]

 [[0.51954421 0.7052495  0.88464003]
  [0.55991119 0.1391293  0.92157967]
  [0.43259494 0.48403044 0.26987481]]

 [[0.09059209 0.47313654 0.56348786]
  [0.01803189 0.6060705  0.80673675]
  [0.66846365 0.53115989 0.62846997]]]


In [10]:
z = np.ones((3,3),dtype=int)
z[1,1]=0
print(z)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr1 = np.sort(arr)
arr2 = arr1[::-1]
print(arr2)

[8 7 6 5 4 3 2 1]


In [12]:
Z = np.random.random((3,3))
print(Z)
print(np.shape(Z))

[[0.68426894 0.20625546 0.81668786]
 [0.15379284 0.15690831 0.36362119]
 [0.44376239 0.32930743 0.89814379]]
(3, 3)


In [13]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [14]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


In [15]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стив Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0   Джеки Джексон       38      True
1  Стив Стивенсон       25     False

In [16]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [17]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [18]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [19]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [23]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([5, 4, 3, 2, 1])
d = 0
for i in range(1,len(s1)):
    d += (s1[i] - s2[i])**2
print(d)

24


In [24]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

In [26]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [27]:
dataframe.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [31]:
dataframe[dataframe['gender'] == 'Male'].head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

In [3]:
import numpy as np
from sklearn import preprocessing
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [7]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


In [9]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00, 20, 90.95, 96.27, 91.21],
                       'B':[103.02, 107.26, 110.35, 114.23, 114.68],
                       'C':['big', 'small', 'big', 'small', 'small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.072931  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
first_scaler = MinMaxScaler()
second_scaler = StandardScaler()
dataframe[['sepal_length_cm']] = first_scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = second_scaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]